# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - now.md
  

footer: '<a href="https://merveilles.town/web/accounts/6363">dokoissho@merveilles.town</a> | MIT License 2021'

theme: jekyll-theme-console

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
